# Zharp shell integration for zsh - CANONICAL COPY.
#
# What it does: marks where each prompt starts with OSC 133;A, reports the
# working directory with OSC 7, and appends OSC 133;B to PS1 so Zharp knows
# which column typed input begins at. Together these drive command blocks and
# the live directory sidebar.
#
# How the app uses it: Zharp writes this text to
# ~/Library/Application Support/Zharp/shell/zsh/.zshrc and launches zsh with
# ZDOTDIR pointed at that folder. The script sources the user's own zsh files
# first (via ZHARP_USER_ZDOTDIR), so nothing of their setup is bypassed.
#
# This file is the canonical copy. The applications do NOT read it at runtime:
# each app embeds its own generated copy of the body below, as a string literal
# in its source. Editing this file alone changes nothing that ships.
#
# If you edit the body below, you MUST update every embedded copy to match:
#   macOS:   macos/Sources/ZharpApp/ShellDiscovery.swift
# Then run scripts/check-shared-drift.sh, which fails the build when this file
# and the embedded copies disagree.
#
# Everything above the sentinel line is header and is ignored by the drift
# check. Everything below it is compared byte for byte against the embedded
# copies, after the language specific string escaping has been undone.
# zharp-canonical-body-begins-below
# Generated by Zharp - do not edit. Sources your own zsh setup, then
# reports the prompt position (OSC 133;A) and working directory (OSC 7).
ZDOTDIR="${ZHARP_USER_ZDOTDIR:-$HOME}"
[[ -f "$ZDOTDIR/.zshenv" ]] && source "$ZDOTDIR/.zshenv"
[[ -f "$ZDOTDIR/.zprofile" ]] && source "$ZDOTDIR/.zprofile"
[[ -f "$ZDOTDIR/.zshrc" ]] && source "$ZDOTDIR/.zshrc"
[[ -f "$ZDOTDIR/.zlogin" ]] && source "$ZDOTDIR/.zlogin"

__zharp_mark() {
  printf '\033]133;A\007'
  printf '\033]7;file://%s%s\033\\' "${HOST}" "${PWD}"
  # OSC 133;B has to sit at the END of the prompt, so it rides on PS1
  # rather than this hook. Re-checked every prompt because themes like
  # powerlevel10k rebuild PS1 on each render.
  if [[ "$PS1" != *$'\033]133;B\007'* ]]; then
    PS1="${PS1}"$'%{\033]133;B\007%}'
  fi
}

# zsh runs a standalone `precmd` function BEFORE everything in
# precmd_functions, and prompt themes print their preprompt (the path
# or git line above the caret) from exactly there. Hooking the array
# alone would put our mark after those lines, so they would fall into
# the PREVIOUS block and its copied output would end with the next
# prompt. Wrapping precmd puts the mark genuinely first.
__zharp_wrap_precmd() {
  if (( $+functions[precmd] )); then
    [[ $functions[precmd] == *__zharp_mark* ]] && return
    functions[__zharp_theme_precmd]=$functions[precmd]
    precmd() { __zharp_mark; __zharp_theme_precmd "$@" }
  else
    precmd() { __zharp_mark }
  fi
}
__zharp_wrap_precmd
# A theme that installs its prompt lazily replaces precmd on the first
# render, so re-wrap once per prompt; the guard above makes it a no-op
# when we are already in place.
autoload -Uz add-zsh-hook 2>/dev/null && add-zsh-hook precmd __zharp_wrap_precmd
