# Zharp shell integration for bash - CANONICAL COPY.
#
# What it does: marks where each prompt starts with OSC 133;A, reports the
# working directory with OSC 7, and appends OSC 133;B to PS1 so Zharp knows
# which column typed input begins at. Together these drive command blocks and
# the live directory sidebar.
#
# How the app uses it: Zharp writes this text to
# ~/Library/Application Support/Zharp/shell/bash/zharp.bash and launches bash
# with --rcfile pointing at it. The script sources the user's own bash startup
# files first, so nothing of their setup is bypassed.
#
# This file is the canonical copy. The applications do NOT read it at runtime:
# each app embeds its own generated copy of the body below, as a string literal
# in its source. Editing this file alone changes nothing that ships.
#
# If you edit the body below, you MUST update every embedded copy to match:
#   macOS:   macos/Sources/ZharpApp/ShellDiscovery.swift
# Then run scripts/check-shared-drift.sh, which fails the build when this file
# and the embedded copies disagree.
#
# Everything above the sentinel line is header and is ignored by the drift
# check. Everything below it is compared byte for byte against the embedded
# copies, after the language specific string escaping has been undone.
# zharp-canonical-body-begins-below
# Generated by Zharp - do not edit. Sources your own bash setup, then
# reports the prompt position (OSC 133;A) and working directory (OSC 7).
[[ -f /etc/bashrc ]] && source /etc/bashrc
for f in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
  [[ -f "$f" ]] && source "$f" && break
done
[[ -f "$HOME/.bashrc" ]] && source "$HOME/.bashrc"

__zharp_report() {
  printf '\033]133;A\007'
  printf '\033]7;file://%s%s\033\\' "${HOSTNAME}" "${PWD}"
  # OSC 133;B marks where input starts, so it belongs at the end of PS1.
  # \[ \] keeps bash from counting it toward the prompt width.
  if [[ "$PS1" != *'133;B'* ]]; then
    PS1="${PS1}\[\033]133;B\007\]"
  fi
}
case "$PROMPT_COMMAND" in
  *__zharp_report*) ;;
  "") PROMPT_COMMAND="__zharp_report" ;;
  *) PROMPT_COMMAND="__zharp_report; $PROMPT_COMMAND" ;;
esac
