import Foundation

/// Everything needed to launch one shell flavor.
struct ShellSpec {
    let arguments: [String]
    let displayName: String
    let extraEnvironment: [String: String?]?
}

/// Finds installed shells and builds their launch command lines.
///
/// Where the Windows build injects a PowerShell `prompt` wrapper, this writes
/// small rc snippets into the app support folder and points each shell at them.
/// Every hook emits OSC 133;A (prompt mark, drives the block
/// rendering) followed by OSC 7 (working directory, drives the live sidebar
/// path), then hands control back to the user's own prompt. The prompt itself
/// ends with OSC 133;B, marking the column where typed input begins - that is
/// what lets Zharp read back the command a block ran.
enum ShellDiscovery {

    /// Where the generated rc files live: ~/Library/Application Support/Zharp/shell.
    private static var integrationDirectory: URL {
        AppSettings.supportDirectory.appendingPathComponent("shell", isDirectory: true)
    }

    /// Resolves a shell id ("auto"/"zsh"/"bash"/"fish"/"pwsh"/"sh").
    static func shell(for preference: String?) -> ShellSpec {
        switch preference?.lowercased() {
        case "bash": return bash()
        case "fish": return fish() ?? zsh()
        case "pwsh": return pwsh() ?? zsh()
        case "sh": return ShellSpec(arguments: ["/bin/sh", "-i"], displayName: "sh",
                                    extraEnvironment: nil)
        case "zsh": return zsh()
        default: return auto()
        }
    }

    /// The user's login shell from the password database, like Terminal.app.
    private static func auto() -> ShellSpec {
        let loginShell = ProcessInfo.processInfo.environment["SHELL"] ?? "/bin/zsh"
        switch (loginShell as NSString).lastPathComponent {
        case "bash": return bash(path: loginShell)
        case "fish": return fish(path: loginShell) ?? zsh()
        case "sh": return ShellSpec(arguments: [loginShell, "-i"], displayName: "sh",
                                    extraEnvironment: nil)
        default: return zsh(path: FileManager.default.isExecutableFile(atPath: loginShell)
                            ? loginShell : "/bin/zsh")
        }
    }

    /// Shells actually present on this machine, for the new-tab menu.
    static func availableShells() -> [(id: String, name: String)] {
        var shells: [(String, String)] = []
        if FileManager.default.isExecutableFile(atPath: "/bin/zsh") {
            shells.append(("zsh", "zsh"))
        }
        if FileManager.default.isExecutableFile(atPath: "/bin/bash") || findOnPath("bash") != nil {
            shells.append(("bash", "bash"))
        }
        if findOnPath("fish") != nil {
            shells.append(("fish", "fish"))
        }
        if findOnPath("pwsh") != nil {
            shells.append(("pwsh", "PowerShell"))
        }
        shells.append(("sh", "sh"))
        return shells
    }

    static var isPwshAvailable: Bool { findOnPath("pwsh") != nil }

    // ------------------------------------------------------------ zsh

    /// zsh reads its interactive rc from $ZDOTDIR, so Zharp points ZDOTDIR at a
    /// generated folder whose .zshrc sources the user's own first and then adds
    /// the prompt hook. This is the standard way editors integrate with zsh and
    /// leaves the user's configuration untouched.
    private static func zsh(path: String = "/bin/zsh") -> ShellSpec {
        let userZdotdir = ProcessInfo.processInfo.environment["ZDOTDIR"] ?? NSHomeDirectory()
        let dir = integrationDirectory.appendingPathComponent("zsh", isDirectory: true)
        let script = """
        # Generated by Zharp - do not edit. Sources your own zsh setup, then
        # reports the prompt position (OSC 133;A) and working directory (OSC 7).
        ZDOTDIR="${ZHARP_USER_ZDOTDIR:-$HOME}"
        [[ -f "$ZDOTDIR/.zshenv" ]] && source "$ZDOTDIR/.zshenv"
        [[ -f "$ZDOTDIR/.zprofile" ]] && source "$ZDOTDIR/.zprofile"
        [[ -f "$ZDOTDIR/.zshrc" ]] && source "$ZDOTDIR/.zshrc"
        [[ -f "$ZDOTDIR/.zlogin" ]] && source "$ZDOTDIR/.zlogin"

        __zharp_mark() {
          printf '\\033]133;A\\007'
          printf '\\033]7;file://%s%s\\033\\\\' "${HOST}" "${PWD}"
          # OSC 133;B has to sit at the END of the prompt, so it rides on PS1
          # rather than this hook. Re-checked every prompt because themes like
          # powerlevel10k rebuild PS1 on each render.
          if [[ "$PS1" != *$'\\033]133;B\\007'* ]]; then
            PS1="${PS1}"$'%{\\033]133;B\\007%}'
          fi
        }

        # zsh runs a standalone `precmd` function BEFORE everything in
        # precmd_functions, and prompt themes print their preprompt (the path
        # or git line above the caret) from exactly there. Hooking the array
        # alone would put our mark after those lines, so they would fall into
        # the PREVIOUS block and its copied output would end with the next
        # prompt. Wrapping precmd puts the mark genuinely first.
        __zharp_wrap_precmd() {
          if (( $+functions[precmd] )); then
            [[ $functions[precmd] == *__zharp_mark* ]] && return
            functions[__zharp_theme_precmd]=$functions[precmd]
            precmd() { __zharp_mark; __zharp_theme_precmd "$@" }
          else
            precmd() { __zharp_mark }
          fi
        }
        __zharp_wrap_precmd
        # A theme that installs its prompt lazily replaces precmd on the first
        # render, so re-wrap once per prompt; the guard above makes it a no-op
        # when we are already in place.
        autoload -Uz add-zsh-hook 2>/dev/null && add-zsh-hook precmd __zharp_wrap_precmd
        """
        write(script, to: dir.appendingPathComponent(".zshrc"))
        // .zshenv is read for every zsh, including non-interactive ones; keep
        // it minimal so scripts spawned from the session behave normally.
        write("# Generated by Zharp.\n", to: dir.appendingPathComponent(".zshenv"))

        return ShellSpec(
            arguments: [path, "-i", "-l"],
            displayName: "zsh",
            extraEnvironment: [
                "ZDOTDIR": dir.path,
                "ZHARP_USER_ZDOTDIR": userZdotdir,
            ])
    }

    // ------------------------------------------------------------ bash

    private static func bash(path: String? = nil) -> ShellSpec {
        let exe = path ?? (findOnPath("bash") ?? "/bin/bash")
        let rc = integrationDirectory.appendingPathComponent("bash/zharp.bash")
        let script = """
        # Generated by Zharp - do not edit. Sources your own bash setup, then
        # reports the prompt position (OSC 133;A) and working directory (OSC 7).
        [[ -f /etc/bashrc ]] && source /etc/bashrc
        for f in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
          [[ -f "$f" ]] && source "$f" && break
        done
        [[ -f "$HOME/.bashrc" ]] && source "$HOME/.bashrc"

        __zharp_report() {
          printf '\\033]133;A\\007'
          printf '\\033]7;file://%s%s\\033\\\\' "${HOSTNAME}" "${PWD}"
          # OSC 133;B marks where input starts, so it belongs at the end of PS1.
          # \\[ \\] keeps bash from counting it toward the prompt width.
          if [[ "$PS1" != *'133;B'* ]]; then
            PS1="${PS1}\\[\\033]133;B\\007\\]"
          fi
        }
        case "$PROMPT_COMMAND" in
          *__zharp_report*) ;;
          "") PROMPT_COMMAND="__zharp_report" ;;
          *) PROMPT_COMMAND="__zharp_report; $PROMPT_COMMAND" ;;
        esac
        """
        write(script, to: rc)
        return ShellSpec(arguments: [exe, "--rcfile", rc.path, "-i"],
                         displayName: "bash", extraEnvironment: nil)
    }

    // ------------------------------------------------------------ fish

    private static func fish(path: String? = nil) -> ShellSpec? {
        guard let exe = path ?? findOnPath("fish") else { return nil }
        // fish runs -C after its own config, so the hook simply registers an
        // event function; nothing of the user's setup is bypassed.
        // The event hook covers OSC 133;A and the cwd; OSC 133;B has to follow
        // the prompt's own output, so fish_prompt is copied aside and wrapped.
        let hook = "function __zharp_report --on-event fish_prompt; "
            + "printf '\\e]133;A\\a'; "
            + "printf '\\e]7;file://%s%s\\e\\\\' (hostname) \"$PWD\"; end; "
            + "if not functions -q __zharp_orig_prompt; "
            + "functions --copy fish_prompt __zharp_orig_prompt; "
            + "function fish_prompt; __zharp_orig_prompt; printf '\\e]133;B\\a'; end; end"
        return ShellSpec(arguments: [exe, "-i", "-C", hook],
                         displayName: "fish", extraEnvironment: nil)
    }

    // ------------------------------------------------------------ pwsh

    /// PowerShell 7 on macOS, with the same prompt wrapper the Windows build
    /// injects - so a session started here reports its cwd identically.
    private static func pwsh() -> ShellSpec? {
        guard let exe = findOnPath("pwsh") else { return nil }
        let integration =
            "$global:__zharpPrompt = $function:prompt; " +
            "function global:prompt { " +
            "[Console]::Write(([char]27)+']133;A'+([char]7)+([char]27)+']7;file://'+$PWD.Path+([char]7)); " +
            "(( & $global:__zharpPrompt ) -join '') + ([char]27)+']133;B'+([char]7) }"
        return ShellSpec(arguments: [exe, "-NoLogo", "-NoExit", "-Command", integration],
                         displayName: "PowerShell", extraEnvironment: nil)
    }

    // ------------------------------------------------------------ helpers

    private static func write(_ contents: String, to url: URL) {
        do {
            try FileManager.default.createDirectory(at: url.deletingLastPathComponent(),
                                                    withIntermediateDirectories: true)
            // Rewrite only when the content changed, so an open session's rc
            // file is not churned on every launch.
            if let existing = try? String(contentsOf: url, encoding: .utf8), existing == contents {
                return
            }
            try contents.write(to: url, atomically: true, encoding: .utf8)
        } catch {
            App.log("Writing shell integration to \(url.path) failed: \(error)")
        }
    }

    static func findOnPath(_ fileName: String) -> String? {
        var searchPath = ProcessInfo.processInfo.environment["PATH"] ?? ""
        // A GUI app inherits a minimal PATH; include the usual install roots so
        // Homebrew shells are found the way they are from a login shell.
        searchPath += ":/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
        for dir in searchPath.split(separator: ":") where !dir.isEmpty {
            let candidate = (String(dir) as NSString).appendingPathComponent(fileName)
            if FileManager.default.isExecutableFile(atPath: candidate) {
                return candidate
            }
        }
        return nil
    }
}
